### ISSUE TITLE
Exception bubbling up to the top level

### ISSUE THREAD

**Issue by erikd** [snoyberg/http-client#271] opened 2017-04-12 05:49 UTC
Hi MIchael,

I've been tracking a bug in one of our complex multi-threaded programs in which an exception bubbles up through the various layers (network/tls/connection/http-client-tls/amazonka) and since it doesn't get caught and handled anywhere ends up with our process being killed, resulting sadness.

I've managed to catch a partial call stack:
```
An unknown exception was caught: Network.Socket.recvBuf
CallStack (from HasCallStack):
  recvBuf, called at Network/Socket/ByteString.hsc:234:12 in
    network-2.6.3.1-G4Up1CPKbp7DeFsnywOnGG:Network.Socket.ByteString
  recv, called at ./Network/TLS/Backend.hs:71:12 in
    tls-1.3.10-IZY2QePe4FWIBbEFxaIJ1B:Network.TLS.Backend
  safeRecv, called at ./Network/TLS/Backend.hs:89:30 in
    tls-1.3.10-IZY2QePe4FWIBbEFxaIJ1B:Network.TLS.Backend
  loop, called at ./Network/TLS/Backend.hs:92:46 in
    tls-1.3.10-IZY2QePe4FWIBbEFxaIJ1B:Network.TLS.Backend
  loop, called at ./Network/TLS/Backend.hs:92:46 in
    tls-1.3.10-IZY2QePe4FWIBbEFxaIJ1B:Network.TLS.Backend
  recvAll, called at ./Network/TLS/Backend.hs:82:87 in
    tls-1.3.10-IZY2QePe4FWIBbEFxaIJ1B:Network.TLS.Backend
  backendRecv, called at ./Network/TLS/Backend.hs:51:7 in
    tls-1.3.10-IZY2QePe4FWIBbEFxaIJ1B:Network.TLS.Backend
  $, called at ./Network/TLS/Context/Internal.hs:154:61 in
    tls-1.3.10-IZY2QePe4FWIBbEFxaIJ1B:Network.TLS.Context.Internal
  contextRecv, called at ./Network/TLS/IO.hs:46:23 in
    tls-1.3.10-IZY2QePe4FWIBbEFxaIJ1B:Network.TLS.IO
  readExact, called at ./Network/TLS/IO.hs:71:44 in
    tls-1.3.10-IZY2QePe4FWIBbEFxaIJ1B:Network.TLS.IO
  recvRecord, called at ./Network/TLS/IO.hs:94:20 in
    tls-1.3.10-IZY2QePe4FWIBbEFxaIJ1B:Network.TLS.IO
  recvPacket, called at ./Network/TLS/Core.hs:95:39 in
    tls-1.3.10-IZY2QePe4FWIBbEFxaIJ1B:Network.TLS.Core
  f, called at ./Network/TLS/Context/Internal.hs:231:56 in
    tls-1.3.10-IZY2QePe4FWIBbEFxaIJ1B:Network.TLS.Context.Internal
  withReadLock, called at ./Network/TLS/Core.hs:95:20 in
    tls-1.3.10-IZY2QePe4FWIBbEFxaIJ1B:Network.TLS.Core
  recvData, called at ./Network/Connection.hs:313:42 in
    connection-0.2.8-LVedQnRZu8yJcxKN32iEK9:Network.Connection
  connectionGetChunkBase, called at ./Network/Connection.hs:279:5 in
    connection-0.2.8-LVedQnRZu8yJcxKN32iEK9:Network.Connection
  connectionGetChunk, called at ./Network/HTTP/Client/TLS.hs:170:6 in
    http-client-tls-0.3.4.1-ET48O1daG3cFc3H3v0qj6q:Network.HTTP.Client.TLS
  r, called at ./Network/HTTP/Client/Connection.hs:115:30 in
    http-client-0.5.6.1-1QGzoKBh8X78Xfbq91zAZY:Network.HTTP.Client.Connection
  makeConnection, called at ./Network/HTTP/Client/TLS.hs:169:26 in
    http-client-tls-0.3.4.1-ET48O1daG3cFc3H3v0qj6q:Network.HTTP.Client.TLS
  convertConnection, called at ./Network/HTTP/Client/TLS.hs:138:9 in
    http-client-tls-0.3.4.1-ET48O1daG3cFc3H3v0qj6q:Network.HTTP.Client.TLS
  getTlsConnection, called at ./Network/HTTP/Client/TLS.hs:94:30 in
    http-client-tls-0.3.4.1-ET48O1daG3cFc3H3v0qj6q:Network.HTTP.Client.TLS
  mkManagerSettingsContext', called at ./Network/HTTP/Client/TLS.hs:83:46 in
    http-client-tls-0.3.4.1-ET48O1daG3cFc3H3v0qj6q:Network.HTTP.Client.TLS
  mkManagerSettingsContext, called at ./Network/HTTP/Client/TLS.hs:67:21 in
    http-client-tls-0.3.4.1-ET48O1daG3cFc3H3v0qj6q:Network.HTTP.Client.TLS
  mkManagerSettings, called at ./Network/HTTP/Client/TLS.hs:122:22 in
    http-client-tls-0.3.4.1-ET48O1daG3cFc3H3v0qj6q:Network.HTTP.Client.TLS:
      resource vanished (Connection reset by peer)
```
Unfortunately, the trail goes cold at `mkManagerSettings` and I can't figure out whats calling that. I'm know its somewhere in the Amazonka package, but that package is huge.

My main question is whether this exception should be caught by `http-client-tls` and turned into a `HttpExceptionRequest` for which our code (which sits on top of Amazonka) already has the ability to handle and retry.

Our program which triggers this is the `s3` executable in the `mismi-s3` cabal package of the  [mismi](https://github.com/ambiata/mismi) project. I'm currently building my test exectuable against the git HEAD versions of network, tls, connection and http-client-tls packages with an extra commit to add `HasCallStack` magic all over.

We are pretty sure that our `s3` execuable is hitting this problem due to Amazon s3 rate limiting. When the rate limiting kicks in, it kills the longest running download which seems to need to be at least 50gig.

All the code I'm hacking on here is open source and everything except mismi is on Hackage. Anything else you need to know? Main question is whether https-client-tls should be catching this and wrapping it in a `HttpExceptionRequest`.

**Comment by erikd** [comment] 2017-04-12 05:56
In my hacked version, `Network/HTTP/Client/TLS.hs:122:` is this line:
```
              | Just (_ :: NC.HostCannotConnect) <- fromException se = se'
```
which suggests that this:
```
                se' = toException $ HttpExceptionRequest req $ InternalException se
```
is not actually working as expected.

**Comment by snoyberg** [comment] 2017-04-12 07:44
I'm having a hard time parsing these comments. What do you think is the code that is currently not working correctly, and what should it be replaced with? I'm not sure what relevance `HostCannotConnect` has (I don't see it in your initial comment), or what that has to do with `se'` not "working as expected."

**Comment by erikd** [comment] 2017-04-12 08:34
Apologies, that brain dump was not fully formed and hence rather inchoerent.

At the moment what I think is happening is:
* `Network.Socket.recvBuf` is throwing an exception (Connection reset by peer).
* That exception should be caught by `managerWrapException` and wrapped in `HttpExceptionRequest` to be passed back up the stack.
* Mismi should be catching the `HttpExceptionRequest` and retrying.

Up until about a minute ago, I thought the second bit above was not happening, but now that seems ridiculous.

I now that that either Amazonka or Mismi is doing something incorrect.

Does that make more sense? Do you agree with this new more rational analysis?

**Comment by snoyberg** [comment] 2017-04-12 08:59
I don't have enough information to guess intelligently what's going on TBH. It _does_ seem unlikely that http-client isn't catching an `IOException` in that function based on how it's written and prior experience. Any chance of minimizing the repro steps?

**Comment by erikd** [comment] 2017-04-12 09:10
The *first* thing I tried was to minimize the reproduction steps, without any results. Now that I know more about what is going on, I should try again.

**Comment by erikd** [comment] 2017-04-18 04:36
I've got a more extensive backtrace here:
```
CallStack (from HasCallStack):
  recvBuf, called at Network/Socket/ByteString.hsc:234:12 in
    network-2.6.3.1-G4Up1CPKbp7DeFsnywOnGG:Network.Socket.ByteString
  recv, called at ./Network/TLS/Backend.hs:71:12 in
    tls-1.3.10-JP8XSo2cDAIFup7mSZFg7R:Network.TLS.Backend
  safeRecv, called at ./Network/TLS/Backend.hs:89:30 in
    tls-1.3.10-JP8XSo2cDAIFup7mSZFg7R:Network.TLS.Backend
  loop, called at ./Network/TLS/Backend.hs:92:46 in
    tls-1.3.10-JP8XSo2cDAIFup7mSZFg7R:Network.TLS.Backend
  recvAll, called at ./Network/TLS/Backend.hs:82:87 in
    tls-1.3.10-JP8XSo2cDAIFup7mSZFg7R:Network.TLS.Backend
  backendRecv, called at ./Network/TLS/Backend.hs:51:7 in
    tls-1.3.10-JP8XSo2cDAIFup7mSZFg7R:Network.TLS.Backend
  $, called at ./Network/TLS/Context/Internal.hs:154:61 in
    tls-1.3.10-JP8XSo2cDAIFup7mSZFg7R:Network.TLS.Context.Internal
  contextRecv, called at ./Network/TLS/IO.hs:46:23 in
    tls-1.3.10-JP8XSo2cDAIFup7mSZFg7R:Network.TLS.IO
  readExact, called at ./Network/TLS/IO.hs:71:44 in
    tls-1.3.10-JP8XSo2cDAIFup7mSZFg7R:Network.TLS.IO
  recvRecord, called at ./Network/TLS/IO.hs:94:20 in
    tls-1.3.10-JP8XSo2cDAIFup7mSZFg7R:Network.TLS.IO
  recvPacket, called at ./Network/TLS/Core.hs:95:39 in
    tls-1.3.10-JP8XSo2cDAIFup7mSZFg7R:Network.TLS.Core
  f, called at ./Network/TLS/Context/Internal.hs:231:56 in
    tls-1.3.10-JP8XSo2cDAIFup7mSZFg7R:Network.TLS.Context.Internal
  withReadLock, called at ./Network/TLS/Core.hs:95:20 in
    tls-1.3.10-JP8XSo2cDAIFup7mSZFg7R:Network.TLS.Core
  recvData, called at ./Network/Connection.hs:313:42 in
    connection-0.2.8-z7fcFB5FY1jzQUEqae7w:Network.Connection
  connectionGetChunkBase, called at ./Network/Connection.hs:279:5 in
    connection-0.2.8-z7fcFB5FY1jzQUEqae7w:Network.Connection
  connectionGetChunk, called at ./Network/HTTP/Client/TLS.hs:172:6 in
    http-client-tls-0.3.4.1-3xAg0VInm7D9l3F9CFrSdg:Network.HTTP.Client.TLS
  r, called at ./Network/HTTP/Client/Connection.hs:115:30 in
    http-client-0.5.6.1-1QGzoKBh8X78Xfbq91zAZY:Network.HTTP.Client.Connection
  connectionRead, called at ./Network/HTTP/Client/Body.hs:137:23 in
    http-client-0.5.6.1-1QGzoKBh8X78Xfbq91zAZY:Network.HTTP.Client.Body
  makeLengthReader, called at ./Network/HTTP/Client/Response.hs:114:45 in
    http-client-0.5.6.1-1QGzoKBh8X78Xfbq91zAZY:Network.HTTP.Client.Response
  getResponse, called at ./Network/HTTP/Client/Core.hs:114:9 in
    http-client-0.5.6.1-1QGzoKBh8X78Xfbq91zAZY:Network.HTTP.Client.Core
  httpRaw', called at ./Network/HTTP/Client/Core.hs:217:25 in
    http-client-0.5.6.1-1QGzoKBh8X78Xfbq91zAZY:Network.HTTP.Client.Core
  http', called at ./Network/HTTP/Client/Core.hs:249:35 in
    http-client-0.5.6.1-1QGzoKBh8X78Xfbq91zAZY:Network.HTTP.Client.Core
  httpRedirect', called at ./Network/HTTP/Client/Core.hs:213:5 in
    http-client-0.5.6.1-1QGzoKBh8X78Xfbq91zAZY:Network.HTTP.Client.Core
  responseOpen, called at ./Network/HTTP/Conduit.hs:358:29 in
    http-conduit-2.2.3.1-GvbhcsAM6oVIQNlueXwrB5:Network.HTTP.Conduit
  http, called at src/Network/AWS/Internal/HTTP.hs:143:39 in
    amazonka-1.4.5-Hl84GbQg2ov2KIkdxql08z:Network.AWS.Internal.HTTP
  perform, called at src/Network/AWS/Internal/HTTP.hs:59:46 in
    amazonka-1.4.5-Hl84GbQg2ov2KIkdxql08z:Network.AWS.Internal.HTTP
  retrier, called at src/Control/Monad/Trans/AWS.hs:279:8 in
    amazonka-1.4.5-Hl84GbQg2ov2KIkdxql08z:Control.Monad.Trans.AWS
  send, called at src/Network/AWS.hs:266:18 in
    amazonka-1.4.5-Hl84GbQg2ov2KIkdxql08z:Network.AWS
  send, called at src/Mismi/S3/Commands.hs:592:8 in
    ambiata-mismi-s3-0.0.1-DZ6tOgxgD235BqGcrIF2zW:Mismi.S3.Commands
  downloadWithRange, called at src/Mismi/S3/Commands.hs:587:33 in
    ambiata-mismi-s3-0.0.1-DZ6tOgxgD235BqGcrIF2zW:Mismi.S3.Commands
  multipartDownload, called at src/Mismi/S3/Commands.hs:564:10 in
    ambiata-mismi-s3-0.0.1-DZ6tOgxgD235BqGcrIF2zW:Mismi.S3.Commands
  downloadWithMode, called at src/Mismi/S3/Commands.hs:549:3 in
    ambiata-mismi-s3-0.0.1-DZ6tOgxgD235BqGcrIF2zW:Mismi.S3.Commands
  download, called at gen/../main/s3.hs:131:40 in
    main:Main: resource vanished (Connection reset by peer)
```
Currently trying to handle this (and retry) in our code (mainly to get a quick fix). Posting this mainly for additional info for now.

**Comment by erikd** [comment] 2017-04-18 07:12
I now have a fix for our application which catches and retries `IOException`s (using `Control.Retry.recovering`). Still pretty sure these `IOException`s should not be escaping the lower levels.

**Comment by erikd** [comment] 2017-04-26 05:55
@snoyberg I've put quite a bit of effort into reproducing this with just http-conduit and warp-tls, without any luck. Should I close this?

**Comment by snoyberg** [comment] 2017-04-26 12:45
Yeah, I think closing makes sense for now. Let me know if you find something new.

**Comment by erikd** [comment] 2017-04-27 06:21
@snoyberg I've got a trival HTTP client built on top of the `http-conduit` package. Quick question, should the `Control.Exception.try` [here](https://github.com/erikd-ambiata/test-https-client-resource-vanished/blob/master/main/https-client.hs#L28) be catching all exceptions? 

Currently it isn't, but I was under the impression that the existence of `HttpExceptionContent` content was to capture all exceptions raised by http-conduit and the libraries it sits on top of. Maybe I've mis-understood something.

**Comment by snoyberg** [comment] 2017-04-27 08:46
I don't know what the repro is here, or what versions of the libraries you're using. I also don't know what exception _isn't_ being caught. Usually repros should include a Stack script header to make it clear what libraries are being used.

And yes, `HttpException` should in theory catch all exceptions (which IMO in retrospect was a bad idea I shouldn't have followed), but there is certainly the possibility of some exception slipping through (though I don't know from what you're saying which one that is).

**Comment by erikd** [comment] 2017-04-28 05:05
The reproduction is finally ready for consumption at [test-https-client-resource-vanished](https://github.com/erikd-ambiata/test-https-client-resource-vanished/). Instructions in the `Readme.md`.

**Comment by snoyberg** [comment] 2017-04-28 05:26
This looks very different than the original bug report. 

@vincenthz what's going on with TLSError vs TLSException?

**Comment by erikd** [comment] 2017-04-28 05:30
Yes, its different. I found this one while trying to reproduce the other one.

**Comment by snoyberg** [comment] 2017-04-28 05:33
Then it would have been a good idea to call that out explicitly.

**Comment by erikd** [comment] 2017-04-28 05:38
@snoyberg Yes, I probably should have, but I suppose I saw this escaping exception and the earlier one as symptoms of the same issue.

**Comment by snoyberg** [comment] 2017-04-28 05:57
@erikd Do you want to try patching http-client-tls to catch the additional exception type? That _should_ just fix the issue (and be unrelated to the original one AFAICT).

**Comment by erikd** [comment] 2017-04-28 06:02
Will do!

**Comment by erikd** [comment] 2017-05-01 03:44
Now with call stack information:
```
*** Exception (reporting due to +RTS -xc): (base:GHC.Exception.SomeException), stack trace: 
  Network.TLS.Context.Internal.throwCore,
  called from Network.TLS.IO.recvPacket,
  called from Network.TLS.Context.Internal.withReadLock,
  called from Network.TLS.Core.recvData,
  called from Network.Connection.connectionGetChunk,
  called from Network.HTTP.Client.TLS.mkManagerSettingsContext,
  called from Network.HTTP.Client.TLS.mkManagerSettings,
  called from Network.HTTP.Client.Manager.getConn,
  called from Network.HTTP.Client.Core.httpRaw',
  called from Network.HTTP.Client.Core.httpRedirect',
  called from Network.HTTP.Client.Core.responseOpen,
  called from Network.HTTP.Conduit.http,
  called from Data.Conduit.Internal.Conduit.connectResume,
  called from Control.Monad.Trans.Resource.runResourceT,
  called from Main.runBodyLength,
  called from Main.runTest,
  called from Main.main
https-client: Error_Packet "partial packet: expecting 16408 bytes, got: 7891"
```
Will try and come up with a fix to make http-client-tls catch this and turn it into a `HttpException`.

**Comment by erikd** [comment] 2017-05-01 04:24
Wow, quite a bit of surgery required to handle this one. The exception is happening in `NC.connectionGetChunk` which is called from:
```
convertConnection :: NC.Connection -> IO Connection
convertConnection conn = makeConnection
    (NC.connectionGetChunk conn)
    (NC.connectionPut conn)
    -- Closing an SSL connection gracefully involves writing/reading
    -- on the socket.  But when this is called the socket might be
    -- already closed, and we get a @ResourceVanished@.
    (NC.connectionClose conn `Control.Exception.catch` \(_ :: IOException) -> return ())
```
There no `Request` there, which makes it a bit difficult to to construct a `HttpExceptionRequest`.  The `convertConnection` function is called from `getTlsConnection` which doesn't have the `Request` data either and `getTlsConnection` is used to set up a field of a `ManagerSettings` struct which also doesn't have any way of reporting or handling errors.

@snoyberg , how would you like to handle this?

**Comment by erikd** [comment] 2017-05-01 04:58
With this trivial patch:
```
diff --git a/http-client-tls/Network/HTTP/Client/TLS.hs b/http-client-tls/Network/HTTP/Client/TLS.hs
index fffb8b3..a36f7dc 100644
--- a/http-client-tls/Network/HTTP/Client/TLS.hs
+++ b/http-client-tls/Network/HTTP/Client/TLS.hs
@@ -157,7 +157,7 @@ getTlsProxyConnection mcontext tls sock = do
 
 convertConnection :: NC.Connection -> IO Connection
 convertConnection conn = makeConnection
-    (NC.connectionGetChunk conn)
+    (NC.connectionGetChunk conn `Control.Exception.catch` \(e :: TLS.TLSError) -> throwIO . userError $ "IO is a lie: " ++ show e)
     (NC.connectionPut conn)
     -- Closing an SSL connection gracefully involves writing/reading
     -- on the socket.  But when this is called the socket might be
```
I can catch this exception and add my own spin and see it bubble to the top and kill my process, but I can't see a good way to handle this in a principled manner.

**Comment by snoyberg** [comment] 2017-05-01 09:00
I just tried this patch to reproduce the bug:

```
--- a/http-client-tls/Network/HTTP/Client/TLS.hs
+++ b/http-client-tls/Network/HTTP/Client/TLS.hs
@@ -95,6 +95,7 @@ mkManagerSettingsContext' mcontext tls sockHTTP sockHTTPS = defaultManagerSettin
         let wrapper se
               | Just (_ :: IOException)          <- fromException se = se'
               | Just (_ :: TLS.TLSException)     <- fromException se = se'
+              | Just (_ :: TLS.TLSError)         <- fromException se = se'
               | Just (_ :: NC.LineTooLong)       <- fromException se = se'
 #if MIN_VERSION_connection(0,2,7)
               | Just (_ :: NC.HostNotResolved)   <- fromException se = se'
@@ -156,7 +157,7 @@ getTlsProxyConnection mcontext tls sock = do
 
 convertConnection :: NC.Connection -> IO Connection
 convertConnection conn = makeConnection
-    (NC.connectionGetChunk conn)
+    (throwIO (TLS.Error_Packet "Some exception") >> NC.connectionGetChunk conn)
     (NC.connectionPut conn)
     -- Closing an SSL connection gracefully involves writing/reading
     -- on the socket.  But when this is called the socket might be
```

With just the second modification, I can reproduce the problem, but the first bit (which seems to be identical to your #273 PR) resolves the problem. In the interest of getting to minimal repros, does this in fact demonstrate the problem?

**Comment by erikd** [comment] 2017-05-01 09:24
I don't currently have access to my test machines. I'll look at this in the morning.

**Comment by erikd** [comment] 2017-05-02 01:06
@snoyberg  I tested your change in https://github.com/snoyberg/http-client/issues/271#issuecomment-298307764 but it does *not* behave the same as my test case. With your `throwIO` the exception is caught in the test program at the top level and printed and the program continues running.

In my test case the program runs for 1-5 minutes before the exception escapes and kills the process.

I think the big difference between your test case and mine is that yours throws an exception *every* time it executes this code path whereas mine doesn't.

I then had a hunch, that this problem may be caused in some way by reusing a `Handle` from a previous connection. I rebuild everything using `connection == 2.5.0` (before the switch from sockets to `Handle` s) but the behavior did not change. The same exception still kills my program.

**Comment by snoyberg** [comment] 2017-05-02 04:22
I don't know why it should make a difference if the exception happens occasionally versus every time, I'd expect the behavior to be the same. The only other thought I had was some kind of impure exception/laziness, but I see no evidence of this in any of the code. Outside of some possibility of the run version of the code running, I don't know what could be causing this behavior.

**Comment by erikd** [comment] 2017-05-02 04:25
Fair enough. I'm going to dig a bit deeper and start instrumenting TLS.

**Comment by erikd** [comment] 2017-05-05 00:29
I've been savaging the code in TLS. Specifically, I've been catching the `Error_Packet` constructor in `Network.TLS.Core.recvData` and doing:

```haskell
        onError e@(Error_Packet _) = do
            setEOF ctx
            E.throwIO (Terminated True "Error_Packet" e)
```
but for some reason the exception still bubbles up to the top (and kills my process).

As an even more savage solution I tried this (emulating the behaviour on end-of-file):
```haskell
        onError e@(Error_Packet _) = do
            setEOF ctx
            putStrLn $ show e    
            return B.empty
```
and that actually prevents the "kill the process" behavior and I do indeed see the `Error_Packet` message on `stdout`.

**Comment by erikd** [comment] 2017-05-05 05:13
> I don't know why it should make a difference if the exception happens occasionally versus every time.

That's a valid question. I have checked and rechecked and your patch https://github.com/snoyberg/http-client/issues/271#issuecomment-298286272 produces behavior thats different  to what I'm tracking. The only possible explanation I can come up with is laziness.

**Comment by erikd** [comment] 2017-05-05 05:56
Wow, that is incredibly scary! I hacked around inside the connection library adding strict-ness annotations on something I hadn't seen before:
```
recv: resource vanished (Connection reset by peer)
```
coming from debug I added to `Network.Connection.connectionGetChunk` . Before the strict-ness (but after the debug) I didn't see this.

**Comment by snoyberg** [comment] 2018-06-28 09:59
Due to no reliable repro, and this being an anti-pattern anyway, closing.

**Closed by snoyberg** 2018-06-28 09:59 UTC
