### ISSUE TITLE
TCP request stalls

### ISSUE THREAD

**Issue by bezirg** [snoyberg/http-client#95] opened 2015-01-14 07:05 UTC
My program does something along these lines:

1. there are a bunch of threads each fetching a distinct list of urls
2. the threads share the same 1 manager
3. the manager has managerResponseTimeout: 10s

The program behaves correctly for some time, until randomly some fetcher threads start to "stall". A thread makes a request to a website but I see with `lsof` that the socket remains in **ESTABLISHED** state, even for hours, until I shutdown the program. 

The website that thread stalls on is random: multiple runs of my program show that it can successfully timeout on the same website.

I tested with multiple combinations of these to no avail:
1. GHC 7.6.3 and GHC 7.8.3
2. http-client 0.4.2.2 and 0.4.6.2
3. network 2.4.2.3 and 2.6.0.2

I also tried to have 1 manager per thread but I have the same behaviour still. Any ideas?

**Comment by snoyberg** [comment] 2015-01-14 07:57
Thanks for the report. I'd need more information than provided here to debug this. Can you try the following:

* Add some tracing statements to the http-client codebase to get an idea of where the stalling is occurring. Is it stalled trying to send or receive, for example?
* A minimal reproducing example would be very helpful.
* Can this be reproduced with a local web server, or is this only with specific remote servers?

**Comment by bezirg** [comment] 2015-01-14 09:55
-I am putting tracing statements right now to the http-client codebase.
While doing that, I stumbled upon this:
```
responseOpenHistory ... =
   body <- brReadSome (responseBody res) 1024
   ....
 res <- httpRedirect (redirectCount req0) go req0
```
and in another place

```
httpRedirect ... =
    ...
    let maxFlush = 1024
   lbs <- brReadSome (responseBody res) maxFlush
   responseClose res
```

Probably it is not related to the bug I am experiencing, but I think this redirects
read 2 times (with brReadSome) the 1024bytes chunk of the header. Will that not lead
to any problems?

- For my case, it is really difficult to reproduce. Sometimes it takes only 15minutes of the program running, or it can take several hours. But when this happens, the socket remains open (ESTABLISHED) forever (until the program stops).

**Comment by snoyberg** [comment] 2015-01-14 09:58
I think the code you're looking at in `responseOpenHistory` is doing something else completely, namely just grabbing a chunk of the body to give more meaningful debug output.

**Comment by snoyberg** [comment] 2015-07-21 01:18
Closing due to lack of repro. If you're able to reproduce, please reopen with more details.

**Closed by snoyberg** 2015-07-21 01:18 UTC
