### ISSUE TITLE
Test-suite failures in `spec-nonet`

### ISSUE THREAD

**Issue by hvr** [snoyberg/http-client#330] opened 2018-02-18 08:24 UTC
With the new improved CI script from #329 I noticed the failures at https://ci.appveyor.com/project/snoyberg/http-client/build/116/job/3kgd791e98791v3q#L790 (also reproduced below for your convenience). It may be worth looking into them as they could point to some real issue.

```
$ cabal new-test -j1 -vnormal+nowrap all
In order, the following will be built (use -v for more details):
 - http-client-0.5.10 (test:spec) (ephemeral targets)
 - http-client-0.5.10 (test:spec-nonet) (ephemeral targets)
 - http-client-openssl-0.2.1.1 (test:spec) (ephemeral targets)
 - http-client-tls-0.3.5.3 (test:spec) (ephemeral targets)
 - http-conduit-2.3.0 (test:test) (ephemeral targets)
Preprocessing test suite 'spec' for http-client-0.5.10..
Building test suite 'spec' for http-client-0.5.10..
Running 1 test suites...
Test suite spec: RUNNING...
Network.HTTP.Client
  Client
    works
    method in URL
      success
      failure
    redirects
      follows redirects
      allows to disable redirect following
    managerModifyResponse
      allows to modify the response status code
      modifies the response body
    managerModifyRequest
      port
      checkResponse
      redirectCount
Finished in 0.7929 seconds
10 examples, 0 failures
Test suite spec: PASS
Test suite logged to: C:\WORK\dist-newstyle\build\x86_64-windows\ghc-7.10.3\http-client-0.5.10\c\spec\test\http-client-0.5.10-spec.log
1 of 1 test suites (1 of 1 test cases) passed.
Preprocessing test suite 'spec-nonet' for http-client-0.5.10..
Building test suite 'spec-nonet' for http-client-0.5.10..
Running 1 test suites...
Test suite spec-nonet: RUNNING...
Network.HTTP.Client.Body
  BodySpec
    chunked, single
    chunked, pieces
    chunked, raw
    chunked, pieces, raw
    length, single
    length, pieces
    gzip
Network.HTTP.Client.Cookie
  CookieSpec
    cookie equality - case insensitive Eq
    domainMatches - case insensitive
    domainMatches - case insensitive, partial
Network.HTTP.Client.Headers
  HeadersSpec
    simple response
    Expect: 100-continue (success)
    Expect: 100-continue (failure)
    100 Continue without expectation is OK
Network.HTTP.Client.RequestBody
  streamFile
    works
Network.HTTP.Client.Request
  case insensitive scheme
    http://example.com
    httP://example.com
    HttP://example.com
    HttPs://example.com
    ftp://example.com
  authentication in url
    passes validation
    add username/password to headers section
  Show Request
    redacts authorization header content
  applyBasicProxyAuth
    Should add a proxy-authorization header
    Should add a proxy-authorization header with the specified username and password.
  extract credentials from a URI
    fetches non-empty username before the first ':'
    after ':' is considered password
    decodes username special characters per RFC3986
    decodes password special characters per RFC3986
    no auth is empty
  requestBuilder
    sends the full request, combining headers and body in the non-streaming case
    sends only headers and returns an action for the body on 'Expect: 100-continue'
Network.HTTP.Client.Response
  ResponseSpec
    basic
    no length
    chunked
    gzip
Network.HTTP.Client
  Client
    fails on empty hostnames #40
      http://
      https://
      http://:8000
      https://:8001
    redirecting #41
    redirectCount=0
    connecting to missing server gives nice error message
    extra headers after 100 #49
      False
      True
    early close on a 413 FAILED [1]
    length zero and chunking zero #108 FAILED [2]
    length zero and chunking FAILED [3]
    length and chunking FAILED [4]
    withResponseHistory and redirect
    should not write to closed connection
Failures:
  test-nonet\Network\HTTP\ClientSpec.hs:188: 
  1) Network.HTTP.Client.Client early close on a 413
       uncaught exception: HttpException (HttpExceptionRequest Request {
         host                 = "localhost"
         port                 = 39241
         secure               = False
         requestHeaders       = []
         path                 = "/"
         queryString          = ""
         method               = "GET"
         proxy                = Nothing
         rawBody              = False
         redirectCount        = 10
         responseTimeout      = ResponseTimeoutDefault
         requestVersion       = HTTP/1.1
       }
        (InternalException Network.Socket.recvBuf: failed (Unknown error)))
  test-nonet\Network\HTTP\ClientSpec.hs:194: 
  2) Network.HTTP.Client.Client length zero and chunking zero #108
       uncaught exception: HttpException (HttpExceptionRequest Request {
         host                 = "localhost"
         port                 = 39242
         secure               = False
         requestHeaders       = []
         path                 = "/"
         queryString          = ""
         method               = "GET"
         proxy                = Nothing
         rawBody              = False
         redirectCount        = 10
         responseTimeout      = ResponseTimeoutDefault
         requestVersion       = HTTP/1.1
       }
        (InternalException Network.Socket.recvBuf: failed (Unknown error)))
  test-nonet\Network\HTTP\ClientSpec.hs:199: 
  3) Network.HTTP.Client.Client length zero and chunking
       uncaught exception: HttpException (HttpExceptionRequest Request {
         host                 = "localhost"
         port                 = 39243
         secure               = False
         requestHeaders       = []
         path                 = "/"
         queryString          = ""
         method               = "GET"
         proxy                = Nothing
         rawBody              = False
         redirectCount        = 10
         responseTimeout      = ResponseTimeoutDefault
         requestVersion       = HTTP/1.1
       }
        (InternalException Network.Socket.recvBuf: failed (Unknown error)))
  test-nonet\Network\HTTP\ClientSpec.hs:204: 
  4) Network.HTTP.Client.Client length and chunking
       uncaught exception: HttpException (HttpExceptionRequest Request {
         host                 = "localhost"
         port                 = 39244
         secure               = False
         requestHeaders       = []
         path                 = "/"
         queryString          = ""
         method               = "GET"
         proxy                = Nothing
         rawBody              = False
         redirectCount        = 10
         responseTimeout      = ResponseTimeoutDefault
         requestVersion       = HTTP/1.1
       }
        (InternalException Network.Socket.recvBuf: failed (Unknown error)))
Randomized with seed 485811944
Finished in 5.8853 seconds
51 examples, 4 failures
spec-nonet.exe: Network.Socket.accept: failed (Interrupted function call (WSAEINTR))
spec-nonet.exe: Network.Socket.accept: failed (Interrupted function call (WSAEINTR))
spec-nonet.exe: Network.Socket.accept: failed (Interrupted function call (WSAEINTR))
spec-nonet.exe: Network.Socket.accept: failed (Interrupted function call (WSAEINTR))
spec-nonet.exe: Network.Socket.accept: failed (Interrupted function call (WSAEINTR))
spec-nonet.exe: Network.Socket.accept: failed (Interrupted function call (WSAEINTR))
spec-nonet.exe: Network.Socket.accept: failed (Interrupted function call (WSAEINTR))
spec-nonet.exe: Network.Socket.accept: failed (Interrupted function call (WSAEINTR))
spec-nonet.exe: Network.Socket.accept: failed (Interrupted function call (WSAEINTR))
Test suite spec-nonet: FAIL
Test suite logged to: C:\WORK\dist-newstyle\build\x86_64-windows\ghc-7.10.3\http-client-0.5.10\c\spec-nonet\test\http-client-0.5.10-spec-nonet.log
0 of 1 test suites (0 of 1 test cases) passed.
cabal.exe: Tests failed for test:spec-nonet from http-client-0.5.10.
Command exited with code 1
```

**Comment by snoyberg** [comment] 2018-02-18 08:40
Thanks, but this is a dupe of #111. Your PRs actually reminded me of this, and I've been looking into it. The failures are coming from the test code itself, _not_ the library, so it doesn't indicate a problem in http-client, but I would really appreciate anyone with Windows network experience having a look.

**Closed by snoyberg** 2018-02-18 08:40 UTC
