### ISSUE TITLE
Could not find module ‘Network.BSD’

### ISSUE THREAD

**Issue by juhp** [snoyberg/http-client#415] opened 2019-10-04 14:39 UTC
For Stackage Nightly:
```
    Building test suite 'test' for http-conduit-2.3.7.1..
    [2 of 2] Compiling Main
    
    /var/stackage/work/unpack-dir/unpacked/http-conduit-2.3.7.1-3cc303adfaedac70c7e3809a66b4df1d502da1d7ea886c76311074bff453acdb/test/main.hs:24:1: error:
        Could not find module ‘Network.BSD’
        Perhaps you meant
          Network.DNS (needs flag -package-key dns-4.0.0)
          Network.IRC (needs flag -package-key irc-0.6.1.0)
          Network.N2O (needs flag -package-key n2o-0.11.1)
        Use -v (or `:set -v` in ghci) to see a list of the files searched for.
       |
    24 | import qualified Network.BSD
       | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by snoyberg** [comment] 2019-10-06 04:06
You probably need to enable the `network3` flag for `http-conduit`.

**Comment by juhp** [comment] 2019-10-07 15:22
Looks like that is not released yet?

**Comment by snoyberg** [comment] 2019-10-07 15:35
Doh, sorry about that, my mistake. I've just uploaded it.

**Comment by juhp** [comment] 2019-10-07 16:27
Thanks!

Now

warp-3.3.3 (Grandfathered dependencies) is out of bounds for:
- [ ] http-conduit-2.3.7.2 (>=3.0.0.2 && < 3.3). Michael Snoyman michael@snoyman.com @snoyberg. @snoyberg. Used by: test-suite

**Comment by snoyberg** [comment] 2019-10-08 05:27
There's a test failure that pops up with newer versions of libraries, and I have no idea where it comes from, so I'm hesitant to relax the upper bound. @kazu-yamamoto @vincenthz any thoughts on what might cause an error like this?

```
HandshakeFailed (Error_Misc "sign failed: RSAError InvalidParameters\nCallStack (from HasCallStack):\n  error, called at ./Network/TLS/Handshake/Key.hs:55:31 in tls-1.5.1-3iwocl3O3f4CSTjzS8VZLi:Network.TLS.Handshake.Key")
  TLS FAILED [1]

Failures:

  test/main.hs:218:9: 
  1) httpLbs TLS
       uncaught exception: HttpException
       HttpExceptionRequest Request {
         host                 = "127.0.0.1"
         port                 = 15453
         secure               = True
         requestHeaders       = []
         path                 = "/"
         queryString          = ""
         method               = "GET"
         proxy                = Nothing
         rawBody              = False
         redirectCount        = 10
         responseTimeout      = ResponseTimeoutDefault
         requestVersion       = HTTP/1.1
       }
        (InternalException (HandshakeFailed (Error_Packet_unexpected "Alert [(AlertLevel_Fatal,InternalError)]" " expected: handshake")))
```

You can see the error appear on CI when building with Cabal https://dev.azure.com/snoyberg/http-client/_build/results?buildId=159

**Comment by kazu-yamamoto** [comment] 2019-10-08 12:12
Looks like https://github.com/vincenthz/hs-tls/pull/394
@snoyberg Could you try to the current `master` of https://github.com/vincenthz/hs-tls?

**Comment by snoyberg** [comment] 2019-10-10 03:59
Yes, I can confirm that that fixes the issue. Since there's no issue with warp itself, I'll relax this upper bound and close the issue.

**Closed** 2019-10-10 04:03 UTC

**Comment by kazu-yamamoto** [comment] 2019-10-10 23:03
I will try to release the next version of `tls`.
