### ISSUE TITLE
Make adverse status codes not throw an exception

### ISSUE THREAD

**Issue by bitemyapp** [snoyberg/http-client#193] opened 2016-04-29 03:11 UTC
I get a lot of people complaining about http-client (usually via http-conduit and wreq) throwing exceptions for error-y status codes.

I think what Python's requests library is going to be less surprising to people:

```
>>> import requests
>>> r = requests.get('http://httpstat.us/401')
>>> r
<Response [401]>
>>> r.status_code
401
>>> r = requests.get('http://httpstat.us/500')
>>> r
<Response [500]>
```

I realize this is a major change, but as usual I think it's something where we're better off the sooner we get it fixed.

**Comment by Yuras** [comment] 2016-04-29 08:55
I'm sure you are aware of [checkStatus](http://hackage.haskell.org/package/http-client-0.4.28/docs/Network-HTTP-Client.html#v:checkStatus). Setting it to always return `Nothing` gives the behavior you what, doesn't it?

Not sure my opinion counts, but I think the default behavior (throwing an exception on non-2xx status) makes perfect sense, and I have a lot of code that relies on that.

**Comment by bitemyapp** [comment] 2016-04-29 20:29
@Yuras my point is about the default path. People coming to Haskell expecting "safety" find exceptions for a _status code_ being non-100/200/300 very surprising.

**Comment by snoyberg** [comment] 2016-05-01 05:34
As the docs mention, this is definitely a contentious issue, with people
having strong reasons on both sides. Breaking the API in a silent way in
such a situation is probably a bad idea.

**Comment by bitemyapp** [comment] 2016-05-01 17:43
@snoyberg no doubt. I do see the benefits of using exceptions for this, but we don't want surprise either way. Long as it's on your radar. I'll chew on it.

**Comment by winterland1989** [comment] 2016-05-24 06:02
Also mentioned in #23 , throwing on non-100/200/300 is okay depending on how you model HTTP protocol, the problem is that one may still want to access the respond body...etc inside the exception handler.

The way to do it with current API is to provide your own `checkStatus`, turn off throwing on non-100/200/300 ,  and check status code afterwards. so i suggest to provide a helper like:

```haskell
-- | turn off throwing on non-100/200/300 respond. 
silentBadStatus :: Request -> Request
silentBadStatus req = req{ checkStatus = \_ _ _ _ -> Nothing}
```

I also ask to move `checkStatus` from request level to manager level, i can't see a particular use case that per-requset granularity `checkStatus` is necessary, but i may miss something here, please discuss on this.

**Comment by snoyberg** [comment] 2016-05-24 07:06
I'm fine with making this a manager level setting as well, like we do with
timeouts. Want to make a PR?

**Comment by winterland1989** [comment] 2016-05-24 07:30
Will take a stab on this later ; )

**Comment by snoyberg** [comment] 2016-06-17 07:59
I've posted a Google Form on Twitter and Reddit about this topic:

https://docs.google.com/forms/d/172VCI-9ikFSXfa1hRu8WYsLBu2F6270IqAv44rVsLhQ/viewform

**Comment by snoyberg** [comment] 2016-06-20 09:36
I think this is the best idea for moving forward I've seen, so I'll be making the relevant changes some time this week: https://www.reddit.com/r/haskell/comments/4oi5us/feedback_requested_how_to_deal_with_exceptions/d4cydjc

**Comment by bitemyapp** [comment] 2016-06-20 15:39
@snoyberg problem is, "parseUrlAllStatus" is not going to sound like what a new person wants when they first use the library. They won't know to use something like that. Most don't even understand the idea of parsing a URL to produce a request which is then executed.

We could have something this easy to use:

```python
>>> r = requests.get('https://api.github.com/user', auth=('user', 'pass'))
>>> r.status_code
200
>>> r.headers['content-type']
'application/json; charset=utf8'
>>> r.encoding
'utf-8'
>>> r.text
u'{"type":"User"...'
>>> r.json()
{u'private_gists': 419, u'total_private_repos': 77, ...}
```

The request manager parts I am not as concerned about as that isn't the sucking chest wound scaring people off. Is there some reason we cannot have something roughly as simple/intuitive as the above for the simple cases not concerned with reusing connections?

**Comment by snoyberg** [comment] 2016-06-20 16:14
Let me clarify exactly what I'm thinking:

* Remove the `Default` and `IsString` instance for `Request`
* Mark `parseUrl` as deprecated, and have it point to `parseRequest`
* Add a new `parseRequest` function with the non-throwing behavior (both in a new breaking version and the current major version)
* Possibly: add a new `parseUrlAndThrow` function (or something like that) with the current `parseUrl` behavior
* Update all docs to recommend using `parseRequest`
* Expose a new `defaultRequest` value which is like `def` but without the throwing behavior (both current and next major version)

Does that set aside your concerns?

As far as your example: I believe the `Network.HTTP.Simple` module _does_ give something basically this simple. The syntax is different and somewhat more verbose since there's not built-in assoc lookup syntax or optional named arguments, but otherwise I feel comfortable with saying that that API is good for end users. Do you have specific improvements there that you'd like to see?

**Comment by bitemyapp** [comment] 2016-06-20 16:28
@snoyberg I'd say go ahead for now and I'll chainsaw it after you have something up.

**Comment by winterland1989** [comment] 2016-06-21 02:12
How about add a quoter for `parseUrl`, so that we can write `[HTTP.url|GET foo:bar@www.qux.com/a|]`. We get both compile time check and easy to read/write code.

**Comment by snoyberg** [comment] 2016-06-21 03:45
I'd rather not pull in template Haskell in this library, it negatively
impacts some systems without full GHC support.

**Comment by winterland1989** [comment] 2016-06-21 04:34
But that can be `CPP`ed anyway, i offer to make a PR if you permit ; )

**Comment by snoyberg** [comment] 2016-06-21 07:08
How about adding it to Network.HTTP.Simple? I get less grief about
dependencies there

**Comment by winterland1989** [comment] 2016-06-21 08:08
That's not so obvious IMHO, maybe discuss it later, after we migrate to `parseRequest`. Overall the migration story is good, Thanks!

**Comment by snoyberg** [comment] 2016-06-21 16:50
First stab at this is available in:

https://github.com/snoyberg/http-client/commit/573a28a6e54b46b2adff7cfec571cfbf9bcc42cb

Ideally, I would have deprecated the `IsString` and `Default` instances for `Request`, but that's apparently not possible. Instead, we'll need to have a major version bump which removes these instances, and then at some point in the future we can add them back with the new behavior. I'll hold off on the removing-instances commit until after we nail down what the next 0.4-series release will look like.

**Comment by snoyberg** [comment] 2016-06-27 07:33
One more call for feedback before I move ahead with this change.

**Comment by bitemyapp** [comment] 2016-06-27 15:24
@snoyberg I don't have any objections, but I didn't ask for code to support a QQ/TH for URL parsing.

I'm not sold on making users parse URIs upfront to begin with.

**Comment by winterland1989** [comment] 2016-06-28 01:38
the name of `parseUrlThrow` is a little implicit IMO cause we have a `MonadThrow` m on return type, but it's not related with the 'throw' behavior we want to express. I prefer something like `parseRequest'` with document, what do you think?

**Comment by snoyberg** [comment] 2016-06-28 03:48
I want to be as implicit as possible in that name. The goal is that we're
trying to get people to cycle off of that function towards parseRequest,
and we want it to be obvious in the name (and the DEPRECATION warning) why
it's not as good.

**Comment by winterland1989** [comment] 2016-06-28 10:36
Fine, i  cant find other problems now.

**Comment by snoyberg** [comment] 2016-06-30 09:34
I've uploaded http-client-0.4.30 to Hackage, which introduces these changes. I'm leaning towards just making a break now and releasing 0.5.0 and, instead of removing the `IsString` instance, changing its behavior. (I do want to get rid of the `Default` instance though, I've been moving away from `data-default` for a while now.)

**Comment by snoyberg** [comment] 2016-06-30 18:00
I've created pull request #206 for the http-client 0.5 release. I'm going to close this issue, and ask for feedback on that PR instead from here out.

**Closed by snoyberg** 2016-06-30 18:00 UTC
