### ISSUE TITLE
TlsException when fetching from github https on Linux

### ISSUE THREAD

**Issue by ndmitchell** [snoyberg/http-client#99] opened 2015-01-17 14:30 UTC
With the code:

    downloadFile :: FilePath -> String -> IO ()
    downloadFile file url = withSocketsDo $ do
        request <- C.parseUrl url
        C.withManager $ \manager -> do
            response <- C.http request manager
            C.responseBody response C.$$+- sinkFile file

And the URL `https://raw.githubusercontent.com/haskell/haskell-platform/master/hptool/src/Releases2014.hs` on my Travis instance I get the error:

    TlsException (Terminated True "received fatal error: BadRecordMac" (Error_Protocol ("remote side fatal error",True,BadRecordMac)))

Trying on Windows it works fine. You can see an instance of the error here: https://travis-ci.org/ndmitchell/hogle/jobs/47288783#L765

**Comment by snoyberg** [comment] 2015-01-17 16:35
I'm unable to reproduce this error on my Linux system. This could be a problem on Travis CI itself, though I'd be surprised.

Pinging @vincenthz, do you have any thoughts?

**Comment by vincenthz** [comment] 2015-01-18 20:06
It has been fixed now in tls 1.2.16. the code reorganization for supporting AEAD cipher broke stream cipher.

**Comment by ndmitchell** [comment] 2015-01-18 21:42
Thanks @vincenthz, seems to be working nicely now - so I suspect it failed because travis jumped for the very latest version. Perhaps somewhere someone could add a grab of a github URL to a travis machine, so it gets automatically caught next time.

**Closed** 2015-01-20 13:22 UTC

**Comment by vincenthz** [comment] 2015-01-20 15:25
@ndmitchell I would very like such a system, but I just haven't found the time to deal with how to do it with travis.

**Comment by ndmitchell** [comment] 2015-01-20 16:03
It's not trivial, but not too hard. I've got a [.travis.yml](https://github.com/ndmitchell/hlint/blob/master/.travis.yml) which kicks off a [shell script](https://github.com/ndmitchell/neil/blob/master/travis.sh) which installs a [Haskell package](https://github.com/ndmitchell/neil/) and then I just run [some Haskell code](https://github.com/ndmitchell/neil/blob/master/src/Cabal.hs#L87) that does the real test.
