### ISSUE TITLE
FailedConnectionException when making requests through many proxies

### ISSUE THREAD

**Issue by dgllghr** [snoyberg/http-client#183] opened 2016-04-04 00:53 UTC
I am working on a HTTP proxy that proxies requests to many parent proxies. When trying to make requests through many different proxies using the same `Manager`, I start getting a `FailedConnectionException` on almost every request after many requests have been made.

Code (heavily inspired by https://github.com/fpco/http-reverse-proxy and https://github.com/erikd/http-proxy):
```
import qualified Data.ByteString.Char8         as BS
import qualified Data.ByteString.Lazy.Char8    as LBS
import           Data.Conduit
import qualified Data.Conduit.List             as CL
import qualified Data.Text                     as T
import qualified Network.HTTP.Client           as HC
import qualified Network.HTTP.Client.Conduit   as HCC
import qualified Network.HTTP.Conduit          as HC
import qualified Network.HTTP.Types            as HT
import qualified Network.Wai                   as Wai

-- I upped the default settings to see if higher numbers would fix the problem, but it didn't work
mgrSettings :: HC.ManagerSettings
mgrSettings =
  HC.tlsManagerSettings { HC.managerConnCount = 512
                        , HC.managerIdleConnectionCount = 1024 }

parentProxyRequest :: HC.Request -> HC.Proxy -> T.Text -> T.Text -> HC.Manager -> (Wai.Response -> IO Wai.ResponseReceived) -> IO Wai.ResponseReceived
parentProxyRequest hreq proxy user pass mgr respond = do
  let hreq' = HCC.applyBasicProxyAuth (E.encodeUtf8 user) (E.encodeUtf8 pass) $ hreq { HC.proxy = Just proxy, HC.cookieJar = Nothing, HC.redirectCount = 0 }
  bracket
    (try $ HC.responseOpen hreq' mgr)
    (either (const $ return ()) HC.responseClose)
    (\case
      Left e -> (respond . errorResponse) e
      Right res -> do
        let conduit = awaitForever (\bs -> yield (Chunk $ fromByteString bs) >> yield Flush)
            src = (HCC.bodyReaderSource . HC.responseBody) res
        respond $ Wai.responseStream
          (HC.responseStatus res)
          (HC.responseHeaders res)
          (\sendChunk flush -> src $= conduit $$ CL.mapM_ (\mb ->
            case mb of
              Flush -> flush
              Chunk b -> sendChunk b)))

errorResponse :: SomeException -> Wai.Response
errorResponse e =
        Wai.responseLBS HT.internalServerError500
                [ (HT.hContentType, "text/plain; charset=utf-8") ]
                $ LBS.fromChunks [BS.pack $ show e]

```

If I use 1000 proxies, I start hitting the connections exceptions just by making a bunch of requests. The following should give you an idea of how it is used (note that this only works for http, not https, which is sufficient to show the issue):
```
run = do
    let proxies = loadProxies -- Loads the 1000 proxies and parses them as Vector (Proxy, user, pass)
    mgr <- HC.newManager mgrSettings
    -- Create the warp application
    let warpSettings = ... -- Construct the warp settings
    Warp.runSettings warpSettings $ handleReqs proxies mgr
        
handleReqs proxies mgr waiReq respond = do
    (proxy, user, pass) <- randomDraw proxies
    let req = reqFromWai waiReq -- Create the HC request from the Wai request (not shown)
    parentProxyRequest req proxy user pass mgr respond

randomDraw :: Vector a -> IO a
randomDraw elems = do
    idx <- getStdRandom (randomR (0, V.length elems - 1))
    return $ elems ! idx
```

Making a lot of requests to the warp endpoint will start resulting in the connection exceptions.

The following situations do *not* result in the connection exceptions when making the same requests:
* Don't set a proxy on the request in `parentProxyRequest`
* Create a new `HC.Manager` for each request
* Always using the same parent proxy

Please let me know if I am doing something wrong, but it looks to me like there might be a problem with managing connections to a large number of proxies. The best workaround that comes to mind is to start a new manager each time a request is made to a proxy for the first time and cache that manager for later use.

**Comment by snoyberg** [comment] 2016-04-05 11:35
It does sound like an issue with http-client and not your test case. Can we try to get this down to something more easily reproducible? What's the minimum number of proxies that we'd need to use to reproduce this? Any chance of reproing with something like Docker-run Squid proxies?

**Comment by dgllghr** [comment] 2016-04-05 16:11
I'll put together a self-contained project that demonstrates the problem and set up some proxies for testing.

In the mean time, I've run some tests and discovered that:
1. the fewer proxies there are, the less often the exception is hit, and
2. with 250 proxies or fewer, I don't see the exception at all, though I don't know if this is a real threshold or if it is just really rare below this number.

I see the exceptions happen very rarely with 300 proxies, so it's hard to tell if there is an arbitrary line somewhere (though I did search the repo for 256 but didn't find anything related :) ).

**Comment by dgllghr** [comment] 2016-04-11 15:14
Hi @snoyberg, Sorry for the delay. I've invited you to a repository that will allow you to the test the connection across 500 proxies. Unfortunately, for the proxies I have to add your IP address for you to use them. If you don't mind committing an IP address from which you want to test to the repo, I can whitelist that IP address to the proxies. If you think that will be a problem, let me know and I'm sure we can figure something out.

**Comment by snoyberg** [comment] 2016-04-12 05:40
I don't have a static IP address, so I don't think that's going to work. Is
there no way to reproduce this with local proxy servers spun up via Docker
or something like that?

Also, out of curiosity: could you test out the latest version of
http-client? I wonder if https://github.com/snoyberg/http-client/issues/185
may be related to this at all.

An alternative to dealing with the static IP issue would be to use a remote
dev box. Let me know if #185 had any impact and, if not, I'll send you an
IP address for an EC2 machine.

**Comment by dgllghr** [comment] 2016-04-12 15:09
Looks like [#185](https://github.com/snoyberg/http-client/issues/185) did not fix this issue. If you could send me the IP of the EC2 box, that would probably be the easiest path forward. I'll also add a docker file and script to the repo so that it's easy to spin up hundreds of local proxies.

**Comment by snoyberg** [comment] 2016-04-13 07:27
OK, how about 52.5.20.252?

**Comment by snoyberg** [comment] 2016-04-13 07:31
Also, looking over the repo you showed me, I'm not clear on what the repro is. Are you saying that the bug only manifests in the situation of trying to create your own proxy server? Is there no way of triggering it just by making many normal requests through a bunch of proxies?

**Comment by snoyberg** [comment] 2016-04-13 08:09
And one other point: you haven't actually included the text of the error message you received. It could be generated by lots of things, including just running out of file descriptors. Are you sure your ulimits are high enough to support this many open connections?

**Comment by dgllghr** [comment] 2016-04-13 20:02
Okay, I've added that address to the whitelist. The ulimit is a good catch, but when I upped mine to 50,000 I am still hitting the error, so I don't think that's it either.

I set up the repo that way because that's when the bug definitely manifests itself. I'll also add a simpler program that just makes the requests without the Warp front end.

**Comment by snoyberg** [comment] 2016-04-13 20:13
Can you provide the actual error message? It's still unclear to me if this
is an actual bug or simply a connection failing sporadically.

**Comment by dgllghr** [comment] 2016-04-14 00:38
If I print the exception, all I get is `FailedConnectionException "23.27.238.121" 29842`, where 23.27.238.121 is the IP of the proxy.
As for it being sporadic, I would expect some failed connections every once in a while, but after hundreds of requests have been made, every request results in a failed connection.

**Comment by snoyberg** [comment] 2016-04-14 06:07
Alright, I'm getting confused, and kind of feel like I'm pulling teeth. Running the sample doesn't do anything, it obviously needs some kind of incoming requests. I'm _assuming_ I should `export http_proxy=http://localhost:9001` and then make a bunch of `curl` requests all over the place, but it's completely unclear from your report what exactly you did to trigger it. Also, your original report said you got a `FailedConnectionException` "on almost every request", but you now say it's on every request. I also don't know if every exception you get is to the same host/port or different ones.

Please restate this bug report as a clear set of repro statements and a complete description of the errors you're seeing.

Note that I've already spent a fair bit of time on this, I may have to punt back to you to debug soon if this continues dragging out.

**Comment by dgllghr** [comment] 2016-04-14 12:40
I'm sorry if that was originally unclear. I didn't think making many requests to the endpoint would be prohibitive. I did also say "after many requests have been made", but I can understand if that was not exact enough.

If you can't reproduce this, then please close the issue and I'll re-file if/when we know more.

**Comment by snoyberg** [comment] 2016-04-15 08:04
I left this running for a few hours and couldn't reproduce, closing.

**Closed by snoyberg** 2016-04-15 08:04 UTC
